NRM = "\033[0m"
BOLD = "\033[1m"

PRIMARY_COLOR = "\033[38;5;109m"
PRIMARY_COLOR_ALT = "\033[38;5;66m"
SUCCESS_COLOR = "\033[38;5;142m"
SUCCESS_COLOR_ALT = "\033[38;5;100m"
ERROR_COLOR = "\033[38;5;167m"
WARNING_COLOR = "\033[38;5;11m"

KO = $(PRIMARY_COLOR_ALT)"["$(ERROR_COLOR)$(BOLD)" - "$(PRIMARY_COLOR_ALT)"] "
OK = $(PRIMARY_COLOR_ALT)"["$(SUCCESS_COLOR)$(BOLD)" + "$(PRIMARY_COLOR_ALT)"] "
HD = $(PRIMARY_COLOR_ALT)"["$(PROJECT_COLOR)$(NICK)$(PRIMARY_COLOR_ALT)"] "
WN = $(PRIMARY_COLOR_ALT)"["$(WARNING_COLOR)$(BOLD)" i "$(PRIMARY_COLOR_ALT)"] "

SUCCESS_HD = $(PRIMARY_COLOR_ALT)"["$(SUCCESS_COLOR)"SUCCESS"$(PRIMARY_COLOR_ALT)"] "
FAILURE_HD = $(PRIMARY_COLOR_ALT)"["$(ERROR_COLOR)"FAILURE"$(PRIMARY_COLOR_ALT)"] "

MAKING_PROGRESS = $(HD)$(PROJECT_COLOR_ALT)"Genrating "$(NAME)"...\n"$(NRM)
MAKING_SUCCESS = $(SUCCESS_HD)$(SUCCESS_COLOR)$(NAME)" generated!\n"$(NRM)
MAKING_FAILURE = $(FAILURE_HD)$(ERROR_COLOR)$(NAME)" not generated!\n"$(NRM)
MAKING_LIB = $(HD)$(PROJECT_COLOR)$(NAME)$(PRIMARY_COLOR)" is making %s \n"$(NRM)
MADE_LIB = $(HD)$(PROJECT_COLOR)$(NAME)$(PRIMARY_COLOR)" Made all it's dependencies\n"$(NRM)
MAKING_COMMAND = $(HD)$(WN)$(WARNING_COLOR)"=>"$(PROJECT_COLOR_ALT)" Making %s with '$(CMD)'...\n"$(NRM)

COMPILING_OK = $(HD)$(OK)$(PRIMARY_COLOR)$(PRIMARY_COLOR_ALT)$(dir $<)$(PRIMARY_COLOR)$(notdir $<)"\n"$(NRM)
COMPILING_KO = $(HD)$(KO)$(ERROR_COLOR)"* "$(PRIMARY_COLOR_ALT)$(dir $<)$(PRIMARY_COLOR)$(notdir $<)"\n"$(NRM)
COMPILING_DBG = $(HD)$(PROJECT_COLOR)$(NAME)" is compiling in "$(ERROR_COLOR)"debug"$(PROJECT_COLOR)" mode... \'make re\' to compile in production mode\n"$(NRM)
COMPILING_PRD = $(HD)$(PROJECT_COLOR)$(NAME)" is compiling in "$(SUCCESS_COLOR_ALT)"production"$(PROJECT_COLOR)" mode...\n"$(NRM)

CREATE_DIR = $(HD)$(WN)$(PRIMARY_COLOR_ALT)"%s"$(WARNING_COLOR)"%s"$(NRM)"\n"
CREATE_SUBDIR = $(CREATE_DIR)

DEP_NEEDED = $(HD)$(WN)$(WARNING_COLOR)"%s"$(PRIMARY_COLOR_ALT)" is needed to make, aborting...\n"

CLEANING_OBJS = $(HD)$(OK)$(PROJECT_COLOR)"Files cleaned\n"$(NRM)
CLEANING_BINS = $(HD)$(OK)$(PROJECT_COLOR)"Binary cleaned\n"$(NRM)
